// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwlqtvthocbxrzfzajwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3bHF0dnRob2NieHJ6Znphand6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTY0MDQsImV4cCI6MjA3MTc5MjQwNH0.etBNNV14nFsK5s1G7NlAYYhVmU08OfwjYNwdVb61iuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});